# cargo-features = ["profile-rustflags"]

[profile.release]
opt-level = 3
lto = "fat"
# rustflags = ["-Z", "share-generics=y"]

[package]
name = "oxeylyzer"
version = "0.1.0"
authors = ["O_X_E_Y <lucoerlemans37@gmail.com>"]
edition = "2021"

[workspace]
members = ["kbmodel-ui",
    "kbmodel-core",
    "kbmodel-repl"
]

[dependencies]
kbmodel-core = { path = "./kbmodel-core" }
kbmodel-repl = { path = "./kbmodel-repl" }

[dev-dependencies]
diol = { version = "0.8.3", default-features = false }

[[bin]]
name = "oxeylyzer"
path = "./kbmodel-repl/src/bin/main.rs"
