pins = """
..... ..xx.
...x. .xxxx
..... ..x..
"""

[info]
language = "english"
keyboard_type = "ansi"
trigram_precision = 1000

[alternates]
base = 0.9
same_finger_skips = 0.6

[bigrams]
pinky_ring = 0.2
lateral_stretch = 2.0
d_same_finger_ratio = 0.40

[redirects]
base = 1.4
same_finger_skips = 2.2
bad = 4.5
bad_same_finger_skips = 6.0

[rolls]
inward = 1.5
outward = 1.35

[fingers]
speed = 28.0
heatmap = 1.70
scissors = 2.5
onehands = 0.9
lateral_penalty = 1.0
overuse_penalty = 2.5

[fingers.bias]
pinky = 9.0
ring = 14.0
middle = 20.0
index = 20.0
