[info]
language = "english"
keyboard_type = "ansi"
trigram_precision = 1000

[pins]
pins = """
.....  ..xx.
...x.  .xxxx
.....  ..x..
     xx
"""

[finger_to_column]
finger_to_column = """
01233  66789
01233  66789
01233  66789
44444  55555
"""

# Negative values will penalize the total score.
# Set to 0 to exclude form the total score.

[effort.hand]
left = 1.0
right = 1.0

[effort.fingers]
lateral_move = -2.0

[effort.fingers.preference]
pinky = 1.0
ring = 14.0
middle = 20.0
index = 20.0

# Same Finger Skipgrams will be weighted by `base * (1 ^ -n)`
[brigams.same_finger]
base = -1
bad = -1.25

[bigrams.scissors]
base = 0
bad = -2

[trigrams.alternates]
base = 0

[trigrams.redirects]
base = 0.0
bad = -2.0

[trigrams.rolls]
in_roll = 3.0
out_roll = 2.0

[trigrams.one_hands]
base = 1.0
